package com.creatorconnect.project.mapper;

import com.creatorconnect.project.dto.request.ProjectRequest;
import com.creatorconnect.project.dto.request.UpdateProjectRequest;
import com.creatorconnect.project.dto.response.ProjectResponse;
import com.creatorconnect.project.entity.Project;
import com.creatorconnect.project.entity.ProjectStatus;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.UUID;

/**
 * Manual converter between the {@link Project} entity and the project DTOs.
 *
 * <p>Deliberately implemented by hand (no MapStruct / ModelMapper) so the
 * mapping rules stay explicit, auditable, and free of reflection magic.
 * {@code userId} is never read from a DTO — it is injected by the service
 * layer from the authenticated JWT.
 */
@Component
public class ProjectMapper {

    /**
     * Maps a validated {@link ProjectRequest} into a new, unsaved
     * {@link Project} entity owned by the given user.
     *
     * <p>Identity defaults come from the entity itself: UUID generated by
     * Hibernate, {@code status} defaulting to {@code OPEN}, and auditing
     * timestamps filled on persist.
     *
     * @param userId  the owning user's id (from the JWT)
     * @param request the validated create payload
     * @return a transient {@link Project} ready to be persisted
     */
    public Project toEntity(UUID userId, ProjectRequest request) {
        return Project.builder()
                .userId(userId)
                .title(request.getTitle().trim())
                .description(request.getDescription().trim())
                .category(request.getCategory().trim())
                .skillsRequired(normalizeSkills(request.getSkillsRequired()))
                .budget(request.getBudget())
                .duration(request.getDuration().trim())
                .experienceLevel(request.getExperienceLevel().trim())
                .location(normalize(request.getLocation()))
                .status(request.getStatus() != null ? request.getStatus() : ProjectStatus.OPEN)
                .applicationDeadline(request.getApplicationDeadline())
                .build();
    }

    /**
     * Applies the non-{@code null} fields of an {@link UpdateProjectRequest}
     * onto an existing {@link Project} (partial-update semantics).
     *
     * <p>Fields omitted from the request keep their current stored value.
     * The id, userId, and audit timestamps are never touched. An omitted
     * {@code status} keeps the current one; an omitted
     * {@code skillsRequired} keeps the current list.
     *
     * @param project the persisted project to mutate
     * @param request the validated partial-update payload
     */
    public void applyUpdate(Project project, UpdateProjectRequest request) {
        // Required-at-create fields: applied as-is (trimmed). Sending an empty
        // string here is rejected by entity-level validation (@NotBlank), which
        // surfaces as 400.
        if (request.getTitle() != null) {
            project.setTitle(request.getTitle().trim());
        }
        if (request.getDescription() != null) {
            project.setDescription(request.getDescription().trim());
        }
        if (request.getCategory() != null) {
            project.setCategory(request.getCategory().trim());
        }
        if (request.getBudget() != null) {
            project.setBudget(request.getBudget());
        }
        if (request.getDuration() != null) {
            project.setDuration(request.getDuration().trim());
        }
        if (request.getExperienceLevel() != null) {
            project.setExperienceLevel(request.getExperienceLevel().trim());
        }
        // Optional fields: null = unchanged, empty/blank string = clear the field.
        if (request.getLocation() != null) {
            project.setLocation(normalize(request.getLocation()));
        }
        if (request.getStatus() != null) {
            project.setStatus(request.getStatus());
        }
        if (request.getSkillsRequired() != null) {
            project.setSkillsRequired(normalizeSkills(request.getSkillsRequired()));
        }
        if (request.getApplicationDeadline() != null) {
            project.setApplicationDeadline(request.getApplicationDeadline());
        }
    }

    /**
     * Maps a persisted {@link Project} into the API-safe
     * {@link ProjectResponse}.
     *
     * @param project the persisted project
     * @return the response payload
     */
    public ProjectResponse toResponse(Project project) {
        return ProjectResponse.builder()
                .id(project.getId())
                .userId(project.getUserId())
                .title(project.getTitle())
                .description(project.getDescription())
                .category(project.getCategory())
                .skillsRequired(project.getSkillsRequired())
                .budget(project.getBudget())
                .duration(project.getDuration())
                .experienceLevel(project.getExperienceLevel())
                .location(project.getLocation())
                .status(project.getStatus())
                .applicationDeadline(project.getApplicationDeadline())
                .createdAt(project.getCreatedAt())
                .updatedAt(project.getUpdatedAt())
                .build();
    }

    /**
     * Normalizes a skills list: trims every entry, drops null/blank entries,
     * and maps {@code null} to an empty list (a project with no listed skills
     * is valid).
     *
     * @param skills the raw DTO list (may be {@code null})
     * @return a clean, immutable list (never {@code null})
     */
    private List<String> normalizeSkills(List<String> skills) {
        if (skills == null) {
            return List.of();
        }
        return skills.stream()
                .filter(skill -> skill != null && !skill.isBlank())
                .map(String::trim)
                .toList();
    }

    /**
     * Trims a value and maps blank strings to {@code null}.
     *
     * <p>This is what makes optional fields clearable: an update that sends
     * {@code ""} for an optional field removes the stored value instead of
     * persisting an empty string.
     *
     * @param value the raw DTO value (may be {@code null})
     * @return {@code null} for null/blank input, otherwise the trimmed value
     */
    private String normalize(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return value.trim();
    }
}
