package com.creatorconnect.auth.mapper;

import com.creatorconnect.auth.dto.request.RegisterRequest;
import com.creatorconnect.auth.dto.response.RegisterResponse;
import com.creatorconnect.auth.entity.User;
import org.springframework.stereotype.Component;

/**
 * Manual converter between the {@link User} entity and the auth DTOs.
 *
 * <p>Deliberately implemented by hand (no MapStruct / ModelMapper) so the
 * mapping rules stay explicit, auditable, and free of reflection magic.
 * Password encoding is <em>not</em> performed here — the service layer passes
 * the already-encoded hash into {@link #toEntity(RegisterRequest, String)}.
 */
@Component
public class UserMapper {

    /**
     * Maps a validated {@link RegisterRequest} into a new, unsaved
     * {@link User} entity.
     *
     * <p>Identity defaults come from the entity itself: UUID generated by
     * Hibernate, {@code provider = LOCAL}, {@code enabled = true},
     * {@code emailVerified = false}, and auditing timestamps filled on persist.
     *
     * <p>The email is passed explicitly rather than read from the request so
     * the normalized (lowercase) value produced by the service layer is used
     * and the incoming DTO stays untouched.
     *
     * @param request         the validated registration payload
     * @param email           the normalized email to persist
     * @param encodedPassword the BCrypt hash produced by the service layer
     * @return a transient {@link User} ready to be persisted
     */
    public User toEntity(RegisterRequest request, String email, String encodedPassword) {
        return User.builder()
                .firstName(request.getFirstName())
                .lastName(request.getLastName())
                .email(email)
                .password(encodedPassword)
                .phone(request.getPhone())
                .role(request.getRole())
                .build();
    }

    /**
     * Maps a persisted {@link User} into the API-safe {@link RegisterResponse}.
     *
     * <p>The password hash is intentionally omitted from the response.
     *
     * @param user the persisted user
     * @return the response payload
     */
    public RegisterResponse toResponse(User user) {
        return RegisterResponse.builder()
                .id(user.getId())
                .firstName(user.getFirstName())
                .lastName(user.getLastName())
                .email(user.getEmail())
                .phone(user.getPhone())
                .role(user.getRole())
                .provider(user.getProvider())
                .createdAt(user.getCreatedAt())
                .build();
    }
}
