package com.creatorconnect.hiring.mapper;

import com.creatorconnect.hiring.dto.request.ApplicationRequest;
import com.creatorconnect.hiring.dto.response.ApplicationResponse;
import com.creatorconnect.hiring.entity.Application;
import org.springframework.stereotype.Component;

import java.util.UUID;

/**
 * Manual converter between the {@link Application} entity and the application
 * DTOs.
 *
 * <p>Deliberately implemented by hand (no MapStruct / ModelMapper) so the
 * mapping rules stay explicit, auditable, and free of reflection magic.
 * {@code freelancerId} is never read from a DTO — it is injected by the
 * service layer from the authenticated JWT.
 */
@Component
public class ApplicationMapper {

    /**
     * Maps a validated {@link ApplicationRequest} into a new, unsaved
     * {@link Application} entity belonging to the given freelancer.
     *
     * <p>Identity defaults come from the entity itself: UUID generated by
     * Hibernate, {@code status} defaulting to {@code PENDING}, and auditing
     * timestamps filled on persist.
     *
     * @param freelancerId the applying freelancer's id (from the JWT)
     * @param request      the validated create payload
     * @return a transient {@link Application} ready to be persisted
     */
    public Application toEntity(UUID freelancerId, ApplicationRequest request) {
        return Application.builder()
                .projectId(request.getProjectId())
                .freelancerId(freelancerId)
                .proposal(request.getProposal().trim())
                .expectedBudget(request.getExpectedBudget())
                .estimatedDuration(request.getEstimatedDuration().trim())
                .build();
    }

    /**
     * Maps a persisted {@link Application} into the API-safe
     * {@link ApplicationResponse}.
     *
     * @param application the persisted application
     * @return the response payload
     */
    public ApplicationResponse toResponse(Application application) {
        return ApplicationResponse.builder()
                .id(application.getId())
                .projectId(application.getProjectId())
                .freelancerId(application.getFreelancerId())
                .proposal(application.getProposal())
                .expectedBudget(application.getExpectedBudget())
                .estimatedDuration(application.getEstimatedDuration())
                .status(application.getStatus())
                .createdAt(application.getCreatedAt())
                .updatedAt(application.getUpdatedAt())
                .build();
    }
}
