package com.creatorconnect.hiring.mapper;

import com.creatorconnect.hiring.dto.request.ReviewRequest;
import com.creatorconnect.hiring.dto.response.ReviewResponse;
import com.creatorconnect.hiring.entity.Review;
import org.springframework.stereotype.Component;

import java.util.UUID;

/**
 * Manual converter between the {@link Review} entity and the review DTOs.
 *
 * <p>Deliberately implemented by hand (no MapStruct / ModelMapper) so the
 * mapping rules stay explicit, auditable, and free of reflection magic.
 * {@code creatorId} is never read from a DTO — it is injected by the service
 * layer from the authenticated JWT.
 */
@Component
public class ReviewMapper {

    /**
     * Maps a validated {@link ReviewRequest} into a new, unsaved
     * {@link Review} entity authored by the given creator.
     *
     * <p>Identity defaults come from the entity itself: UUID generated by
     * Hibernate, and auditing timestamps filled on persist. The optional
     * {@code reviewText} is trimmed when present.
     *
     * @param creatorId the reviewing creator's id (from the JWT)
     * @param request   the validated create payload
     * @return a transient {@link Review} ready to be persisted
     */
    public Review toEntity(UUID creatorId, ReviewRequest request) {
        return Review.builder()
                .projectId(request.getProjectId())
                .creatorId(creatorId)
                .freelancerId(request.getFreelancerId())
                .rating(request.getRating())
                .reviewText(trimToNull(request.getReviewText()))
                .build();
    }

    /**
     * Maps a persisted {@link Review} into the API-safe {@link ReviewResponse}.
     *
     * @param review the persisted review
     * @return the response payload
     */
    public ReviewResponse toResponse(Review review) {
        return ReviewResponse.builder()
                .id(review.getId())
                .projectId(review.getProjectId())
                .creatorId(review.getCreatorId())
                .freelancerId(review.getFreelancerId())
                .rating(review.getRating())
                .reviewText(review.getReviewText())
                .createdAt(review.getCreatedAt())
                .updatedAt(review.getUpdatedAt())
                .build();
    }

    /**
     * Trims a text value, converting blank/whitespace-only input to
     * {@code null} so an empty optional field is stored as {@code NULL}.
     *
     * @param value the raw input (may be {@code null})
     * @return the trimmed value, or {@code null} when blank
     */
    private String trimToNull(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }
}
