package com.creatorconnect.profile.mapper;

import com.creatorconnect.profile.dto.request.ProfileRequest;
import com.creatorconnect.profile.dto.request.UpdateProfileRequest;
import com.creatorconnect.profile.dto.response.ProfileResponse;
import com.creatorconnect.profile.entity.Profile;
import org.springframework.stereotype.Component;

import java.util.UUID;

/**
 * Manual converter between the {@link Profile} entity and the profile DTOs.
 *
 * <p>Deliberately implemented by hand (no MapStruct / ModelMapper) so the
 * mapping rules stay explicit, auditable, and free of reflection magic.
 * {@code userId} is never read from a DTO — it is injected by the service
 * layer from the authenticated JWT.
 */
@Component
public class ProfileMapper {

    /**
     * Maps a validated {@link ProfileRequest} into a new, unsaved
     * {@link Profile} entity owned by the given user.
     *
     * <p>Identity defaults come from the entity itself: UUID generated by
     * Hibernate, {@code availableForHire} defaulting to {@code true}, and
     * auditing timestamps filled on persist.
     *
     * @param userId  the owning user's id (from the JWT)
     * @param request the validated create payload
     * @return a transient {@link Profile} ready to be persisted
     */
    public Profile toEntity(UUID userId, ProfileRequest request) {
        return Profile.builder()
                .userId(userId)
                .firstName(request.getFirstName().trim())
                .lastName(request.getLastName().trim())
                .headline(normalize(request.getHeadline()))
                .bio(normalize(request.getBio()))
                .profileImageUrl(normalize(request.getProfileImageUrl()))
                .location(normalize(request.getLocation()))
                .website(normalize(request.getWebsite()))
                .linkedin(normalize(request.getLinkedin()))
                .github(normalize(request.getGithub()))
                .skills(normalize(request.getSkills()))
                .experience(request.getExperience())
                .availableForHire(request.getAvailableForHire() != null
                        ? request.getAvailableForHire()
                        : true)
                .build();
    }

    /**
     * Applies the non-{@code null} fields of an {@link UpdateProfileRequest}
     * onto an existing {@link Profile} (partial-update semantics).
     *
     * <p>Fields omitted from the request keep their current stored value.
     * The id, userId, and audit timestamps are never touched.
     *
     * @param profile the persisted profile to mutate
     * @param request the validated partial-update payload
     */
    public void applyUpdate(Profile profile, UpdateProfileRequest request) {
        // Required fields: applied as-is (trimmed). Sending an empty string here
        // is rejected by entity-level validation (firstName/lastName are
        // @NotBlank), which surfaces as 400.
        if (request.getFirstName() != null) {
            profile.setFirstName(request.getFirstName().trim());
        }
        if (request.getLastName() != null) {
            profile.setLastName(request.getLastName().trim());
        }
        // Optional fields: null = unchanged, empty/blank string = clear the field.
        if (request.getHeadline() != null) {
            profile.setHeadline(normalize(request.getHeadline()));
        }
        if (request.getBio() != null) {
            profile.setBio(normalize(request.getBio()));
        }
        if (request.getProfileImageUrl() != null) {
            profile.setProfileImageUrl(normalize(request.getProfileImageUrl()));
        }
        if (request.getLocation() != null) {
            profile.setLocation(normalize(request.getLocation()));
        }
        if (request.getWebsite() != null) {
            profile.setWebsite(normalize(request.getWebsite()));
        }
        if (request.getLinkedin() != null) {
            profile.setLinkedin(normalize(request.getLinkedin()));
        }
        if (request.getGithub() != null) {
            profile.setGithub(normalize(request.getGithub()));
        }
        if (request.getSkills() != null) {
            profile.setSkills(normalize(request.getSkills()));
        }
        if (request.getExperience() != null) {
            profile.setExperience(request.getExperience());
        }
        if (request.getAvailableForHire() != null) {
            profile.setAvailableForHire(request.getAvailableForHire());
        }
    }

    /**
     * Trims a value and maps blank strings to {@code null}.
     *
     * <p>This is what makes optional fields clearable: an update that sends
     * {@code ""} for an optional field removes the stored value instead of
     * persisting an empty string.
     *
     * @param value the raw DTO value (may be {@code null})
     * @return {@code null} for null/blank input, otherwise the trimmed value
     */
    private String normalize(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return value.trim();
    }

    /**
     * Maps a persisted {@link Profile} into the API-safe
     * {@link ProfileResponse}.
     *
     * @param profile the persisted profile
     * @return the response payload
     */
    public ProfileResponse toResponse(Profile profile) {
        return ProfileResponse.builder()
                .id(profile.getId())
                .userId(profile.getUserId())
                .firstName(profile.getFirstName())
                .lastName(profile.getLastName())
                .headline(profile.getHeadline())
                .bio(profile.getBio())
                .profileImageUrl(profile.getProfileImageUrl())
                .location(profile.getLocation())
                .website(profile.getWebsite())
                .linkedin(profile.getLinkedin())
                .github(profile.getGithub())
                .skills(profile.getSkills())
                .experience(profile.getExperience())
                .availableForHire(profile.getAvailableForHire())
                .createdAt(profile.getCreatedAt())
                .updatedAt(profile.getUpdatedAt())
                .build();
    }
}
